# TelkomselCounterApp/telkomsel_main_project/settings.py
# (Pastikan path di bawah ini sesuai dengan lokasi file Anda)

"""
Django settings for telkomsel_main_project project. # Sesuaikan nama proyek di sini

Generated by 'django-admin startproject' using Django X.Y. # Versi Django Anda

For more information on this file, see
https://docs.djangoproject.com/en/X.Y/topics/settings/ # Versi Django Anda

For the full list of settings and their values, see
https://docs.djangoproject.com/en/X.Y/ref/settings/ # Versi Django Anda
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/X.Y/howto/deployment/checklist/ # Versi Django Anda

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-INI_ADALAH_SECRET_KEY_ANDA' # Biarkan ini sesuai yang ada di file Anda

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True # <-- PASTIKAN INI TRUE UNTUK PENGEMBANGAN

ALLOWED_HOSTS = [] # <-- Biarkan ini kosong jika DEBUG = True


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'counters', # <-- Pastikan aplikasi 'counters' terdaftar
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'telkomsel_main_project.urls' # <-- Sesuaikan dengan nama folder proyek utama Anda jika berbeda (misal: 'telkomsel_dashboard.urls')

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'], # <-- TAMBAHKAN INI UNTUK MENEMUKAN TEMPLATE DI ROOT PROJECT
        'APP_DIRS': True, # Biarkan ini True agar Django mencari template di 'templates' di dalam setiap aplikasi
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'telkomsel_main_project.wsgi.application' # <-- Sesuaikan nama folder proyek utama Anda


# Database
# https://docs.djangoproject.com/en/X.Y/ref/settings/#databases # Versi Django Anda

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/X.Y/ref/settings/#auth-password-validators # Versi Django Anda

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/X.Y/topics/i18n/ # Versi Django Anda

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC' # Anda mungkin ingin menggantinya ke Asia/Jakarta

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/X.Y/howto/static-files/ # Versi Django Anda

STATIC_URL = '/static/' # <-- Pengaturan Static yang BENAR dan SATU-SATUNYA

# Tambahkan lokasi folder 'static' di root proyek ke daftar tempat Django mencari file statis
STATICFILES_DIRS = [
    BASE_DIR / 'static', # <-- Pengaturan STATICFILES_DIRS yang BENAR dan SATU-SATUNYA
]


# Settings for media files (uploads)
MEDIA_URL = '/media/' # <-- Pengaturan Media yang BENAR dan SATU-SATUNYA
MEDIA_ROOT = BASE_DIR / 'media' # <-- Pengaturan Media yang BENAR dan SATU-SATUNYA


# Default primary key field type
# https://docs.djangoproject.com/en/X.Y/ref/settings/#default-auto-field # Versi Django Anda

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# URL untuk otentikasi (Ditambahkan sebelumnya)
LOGIN_REDIRECT_URL = '/dashboard/' # Akan dibuat nanti
LOGIN_URL = '/accounts/login/'
LOGOUT_REDIRECT_URL = '/' # Halaman utama setelah logout