# Generated by Django 5.2 on 2025-04-26 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Counter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_counter', models.CharField(max_length=200)),
                ('nama_pemilik', models.CharField(max_length=200)),
                ('nomor_telepon', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('alamat', models.TextField(blank=True, null=True)),
                ('tanggal_bergabung', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
    ]
